register:
    path: /register
    methods: [POST]
    controller: App\Controller\Api\CongregationController::register

all:
    path: /all
    methods: [GET]
    controller: App\Controller\Api\CongregationController::all