register:
    path: /register
    controller: App\Controller\Api\TitheController::register
    methods: [POST]

delete:
    path: /delete/{id}
    controller: App\Controller\Api\TitheController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'


total_with_congregations:
    path: /total
    methods: [GET]
    controller: App\Controller\Api\TitheController::totalWithCongregations

all:
    path: /all
    controller: App\Controller\Api\TitheController::all
    methods: [GET]