<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container98yNk36\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container98yNk36/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container98yNk36.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container98yNk36\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container98yNk36\App_KernelDevDebugContainer([
    'container.build_hash' => '98yNk36',
    'container.build_id' => '1094d933',
    'container.build_time' => 1737474441,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container98yNk36');
