controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    resource: routes/api/auth.yaml
    prefix: api/auth
    name_prefix: auth_

admin:
    resource: routes/api/admin.yaml
    prefix: api/admin
    name_prefix: admin_

congregation:
    resource: routes/api/congregation.yaml
    prefix: api/congregation
    name_prefix: congregation_

congregation_offerings:
    resource: routes/api/congregation_offerings.yaml
    prefix: api/congregation/offering/
    name_prefix: congregation_offering_

member:
    resource: routes/api/member.yaml
    prefix: api/member
    name_prefix: member_

tithe:
    resource: routes/api/tithe.yaml
    prefix: api/tithe
    name_prefix: tithe_